spring.application.name=virtual_jdbc_comparison
spring.threads.virtual.enabled=true
# Increased connection from 30sec to 60sec to avoid request timeouts.
spring.datasource.hikari.connection-timeout=60000
spring.datasource.url=jdbc:postgresql://localhost:5432/virtual_threads_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect